name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the `Cpp` folder contents to be deployed as the site root.
          path: ./Cpp

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
